version: '3.8'
services:
  app-dev:
    build: .
    container_name: jupyter-lab
    command: jupyter lab --ip="0.0.0.0" --LabApp.token="" --allow-root
    ports:
      - 8888:8888
    volumes:
      - .:/code
    networks:
      - localdev
networks:
  localdev: